#ifndef BLE_TYPES_H
#define BLE_TYPES_H

#include <stdint.h>

typedef enum
{
    BLE_STATUS_SUCCESS = 0x00U,
    BLE_STATUS_DEV_IN_BLACKLIST = 0x59U,
    BLE_STATUS_CSRK_NOT_FOUND = 0x5AU,
    BLE_STATUS_IRK_NOT_FOUND = 0x5BU,
    BLE_STATUS_DEV_NOT_FOUND = 0x5CU,
    BLE_STATUS_DEV_NOT_BONDED = 0x5EU,
    BLE_STATUS_INVALID_HANDLE = 0x60U,
    BLE_STATUS_OUT_OF_HANDLE = 0x61U,
    BLE_STATUS_INVALID_OPERATION = 0x62U,
    BLE_STATUS_INSUFFICIENT_RESOURCES = 0x64U,
    BLE_STATUS_SEC_PERMISSION_ERROR = 0x65U,
    BLE_STATUS_ADDRESS_NOT_RESOLVED = 0x70U,
    BLE_STATUS_NO_VALID_SLOT = 0x82U,
    BLE_STATUS_SCAN_WINDOW_SHORT = 0x83U,
    BLE_STATUS_NEW_INTERVAL_FAILED = 0x84U,
    BLE_STATUS_INTERVAL_TOO_LARGE = 0x85U,
    BLE_STATUS_LENGTH_FAILED = 0x86U,
    BLE_STATUS_FAILED = 0x91U,
    BLE_STATUS_INVALID_PARAMS = 0x92U,
    BLE_STATUS_BUSY = 0x93U,
    BLE_STATUS_PENDING = 0x95U,
    BLE_STATUS_ERROR = 0x97U,
    BLE_STATUS_OUT_OF_MEMORY = 0x98U,
    BLE_STATUS_TIMEOUT = 0xFFU
} ble_status_t;

#endif
