#ifndef BLE_CFG_H
#define BLE_CFG_H

#include "subsys/ble/tl/tl.h"

#define CFG_TLBLE_EVT_QUEUE_LENGTH 10
#define CFG_TLBLE_MOST_EVENT_PAYLOAD_SIZE \
	255 /**< Set to 255 with the memory manager and the mailbox */
#define TL_BLE_EVENT_FRAME_SIZE (TL_EVT_HDR_SIZE + CFG_TLBLE_MOST_EVENT_PAYLOAD_SIZE)

#define CFG_TLTRACES_EVT_QUEUE_LENGTH 5
#define CFG_TLTRACES_MOST_EVENT_PAYLOAD_SIZE \
	255 /**< Set to 255 with the memory manager and the mailbox */
#define TL_TRACES_EVENT_FRAME_SIZE (TL_EVT_HDR_SIZE + CFG_TLTRACES_MOST_EVENT_PAYLOAD_SIZE)

#define CFG_BLE_MAX_ATT_MTU (156)

#define CFG_BLE_ATT_VALUE_ARRAY_SIZE (1344)

#define BLE_DEFAULT_ATT_MTU 23
#define BLE_PREP_WRITE_X_ATT(max_att) (DIVC(max_att, BLE_DEFAULT_ATT_MTU - 5) * 2)
#define CFG_BLE_PREPARE_WRITE_LIST_SIZE BLE_PREP_WRITE_X_ATT(CFG_BLE_MAX_ATT_MTU)

#define BLE_MEM_BLOCK_SIZE 32
#define BLE_MEM_BLOCK_X_PTX(n_link) 0
#define BLE_MEM_BLOCK_X_TX(mtu) (DIVC((mtu) + 4U, BLE_MEM_BLOCK_SIZE) + 1)
#define BLE_MEM_BLOCK_X_RX(mtu, n_link) ((DIVC((mtu) + 4U, BLE_MEM_BLOCK_SIZE) + 2U) * (n_link) + 1)
#define BLE_MEM_BLOCK_X_MTU(mtu, n_link) \
	(BLE_MEM_BLOCK_X_TX(mtu) + BLE_MEM_BLOCK_X_PTX(n_link) + BLE_MEM_BLOCK_X_RX(mtu, n_link))
#define BLE_MBLOCKS_SECURE_CONNECTIONS 4
#define BLE_MBLOCKS_CALC(pw, mtu, n_link) \
	((pw) + MAX(BLE_MEM_BLOCK_X_MTU(mtu, n_link), BLE_MBLOCKS_SECURE_CONNECTIONS))
#define CFG_BLE_MBLOCK_COUNT(num_link) \
	(BLE_MBLOCKS_CALC(CFG_BLE_PREPARE_WRITE_LIST_SIZE, CFG_BLE_MAX_ATT_MTU, num_link))

#define CFG_BLE_DATA_LENGTH_EXTENSION 1

#define CFG_BLE_PERIPHERAL_SCA 500

#define CFG_BLE_CENTRAL_SCA 0

#define CFG_BLE_LS_SOURCE                                                          \
	(SHCI_C2_BLE_INIT_CFG_BLE_LS_NOCALIB | SHCI_C2_BLE_INIT_CFG_BLE_LS_OTHER_DEV | \
	 SHCI_C2_BLE_INIT_CFG_BLE_LS_CLK_LSE)

#define CFG_BLE_HSE_STARTUP_TIME 0x148

#define CFG_BLE_MAX_CONN_EVENT_LENGTH (0xFFFFFFFF)

#define CFG_BLE_VITERBI_MODE 1

#define CFG_BLE_OPTIONS                                                                 \
	(SHCI_C2_BLE_INIT_OPTIONS_LL_HOST | SHCI_C2_BLE_INIT_OPTIONS_WITH_SVC_CHANGE_DESC | \
	 SHCI_C2_BLE_INIT_OPTIONS_DEVICE_NAME_RW | SHCI_C2_BLE_INIT_OPTIONS_NO_EXT_ADV |    \
	 SHCI_C2_BLE_INIT_OPTIONS_NO_CS_ALGO2 | SHCI_C2_BLE_INIT_OPTIONS_FULL_GATTDB_NVM |  \
	 SHCI_C2_BLE_INIT_OPTIONS_GATT_CACHING_NOTUSED | SHCI_C2_BLE_INIT_OPTIONS_POWER_CLASS_2_3)

#define CFG_BLE_OPTIONS_EXT                         \
	(SHCI_C2_BLE_INIT_OPTIONS_APPEARANCE_READONLY | \
	 SHCI_C2_BLE_INIT_OPTIONS_ENHANCED_ATT_NOTSUPPORTED)

#define CFG_BLE_MAX_COC_INITIATOR_NBR (32)

#define CFG_BLE_MIN_TX_POWER (0)

#define CFG_BLE_MAX_TX_POWER (0)

#define CFG_BLE_RX_MODEL_CONFIG (SHCI_C2_BLE_INIT_RX_MODEL_AGC_RSSI_LEGACY)

#define CFG_BLE_MAX_ADV_SET_NBR (3)

#define CFG_BLE_MAX_ADV_DATA_LEN (1650)

#define CFG_BLE_TX_PATH_COMPENS (0)

#define CFG_BLE_RX_PATH_COMPENS (0)

#define CFG_BLE_CORE_VERSION (SHCI_C2_BLE_INIT_BLE_CORE_5_4)

#define CFG_BLE_MAX_ADD_EATT_BEARERS (4)

/* Offset for configuration values (see ACI_HAL_WRITE_CONFIG_DATA)
 */
#define CONFIG_DATA_PUBLIC_ADDRESS_OFFSET 0x00U
#define CONFIG_DATA_ER_OFFSET 0x08U
#define CONFIG_DATA_IR_OFFSET 0x18U
#define CONFIG_DATA_RANDOM_ADDRESS_OFFSET 0x2EU
#define CONFIG_DATA_GAP_ADD_REC_NBR_OFFSET 0x34U
#define CONFIG_DATA_SC_KEY_TYPE_OFFSET 0x35U
#define CONFIG_DATA_SMP_MODE_OFFSET 0xB0U
#define CONFIG_DATA_LL_SCAN_CHAN_MAP_OFFSET 0xC0U
#define CONFIG_DATA_LL_BG_SCAN_MODE_OFFSET 0xC1U
#define CONFIG_DATA_LL_RSSI_GOLDEN_RANGE_OFFSET 0xC2U
#define CONFIG_DATA_LL_RPA_MODE_OFFSET 0xC3U
#define CONFIG_DATA_LL_RX_ACL_CTRL_OFFSET 0xC4U
#define CONFIG_DATA_LL_MAX_DATA_EXT_OFFSET 0xD1U

/* Length for configuration values (see ACI_HAL_WRITE_CONFIG_DATA)
 */
#define CONFIG_DATA_PUBLIC_ADDRESS_LEN 6
#define CONFIG_DATA_ER_LEN 16
#define CONFIG_DATA_IR_LEN 16
#define CONFIG_DATA_RANDOM_ADDRESS_LEN 6
#define CONFIG_DATA_GAP_ADD_REC_NBR_LEN 1
#define CONFIG_DATA_SC_KEY_TYPE_LEN 1
#define CONFIG_DATA_SMP_MODE_LEN 1
#define CONFIG_DATA_LL_SCAN_CHAN_MAP_LEN 1
#define CONFIG_DATA_LL_BG_SCAN_MODE_LEN 1
#define CONFIG_DATA_LL_RSSI_GOLDEN_RANGE_LEN 2
#define CONFIG_DATA_LL_RPA_MODE_LEN 1
#define CONFIG_DATA_LL_RX_ACL_CTRL_LEN 2
#define CONFIG_DATA_LL_MAX_DATA_EXT_LEN 8

#define CFG_TX_POWER (0x18) /* -0.15dBm */

/**
 *   Identity root key used to derive IRK and DHK(Legacy)
 */
#define CFG_BLE_IR                                      \
	{                                                   \
		0x12, 0x34, 0x56, 0x78, 0x9A, 0xBC, 0xDE, 0xF0, \
		0x12, 0x34, 0x56, 0x78, 0x9A, 0xBC, 0xDE, 0xF0  \
	}

/**
 * Encryption root key used to derive LTK(Legacy) and CSRK
 */
#define CFG_BLE_ER                                      \
	{                                                   \
		0xFE, 0xDC, 0xBA, 0x09, 0x87, 0x65, 0x43, 0x21, \
		0xFE, 0xDC, 0xBA, 0x09, 0x87, 0x65, 0x43, 0x21  \
	}

#define PRIVACY_DISABLED 0x00
#define PRIVACY_ENABLED 0x02

/**
 * Define PHY
 */
#define ALL_PHYS_PREFERENCE 0x00
#define RX_2M_PREFERRED 0x02
#define TX_2M_PREFERRED 0x02
#define TX_1M 0x01
#define TX_2M 0x02
#define RX_1M 0x01
#define RX_2M 0x02

/**
 * Define Keypress Notification Support
 */
#define CFG_KEYPRESS_NOT_SUPPORTED (0x00)
#define CFG_KEYPRESS_SUPPORTED (0x01)

/**
 * Define IO Authentication
 */
#define CFG_BONDING_MODE (1)
#define CFG_ENCRYPTION_KEY_SIZE_MAX (16)
#define CFG_ENCRYPTION_KEY_SIZE_MIN (8)

/* GAP Address Type
 */
#define GAP_PUBLIC_ADDR 0x00U
#define GAP_STATIC_RANDOM_ADDR 0x01U
#define GAP_RESOLVABLE_PRIVATE_ADDR 0x02U
#define GAP_NON_RESOLVABLE_PRIVATE_ADDR 0x03U

#define USE_FIXED_PIN_FOR_PAIRING_ALLOWED 0x00U
#define USE_FIXED_PIN_FOR_PAIRING_FORBIDDEN 0x01U

#endif
