#ifndef BLE_SIG_UUIDS_H
#define BLE_SIG_UUIDS_H

#define BLE_UUID16(val) ((struct ble_uuid){ .uuid = val, .type = BLE_SVC_UUID_TYPE_16 })
#define BLE_UUID128(val) ((struct ble_uuid){ .uuid = val, .type = BLE_SVC_UUID_TYPE_128 })
#define BLE_SVC_ATTR_RECORDS(num_chars, num_descs) (1 + (2 * (num_chars)) + (num_descs))

enum ble_appearance_uuid {
	BLE_APPEARANCE_UNKNOWN = 0x0000,
	BLE_APPEARANCE_GENERIC_COMPUTER = 0x0040,
	BLE_APPEARANCE_GENERIC_PHONE = 0x0080,
	BLE_APPEARANCE_PHONE_SMARTPHONE = 0x0081,
	BLE_APPEARANCE_GENERIC_WATCH = 0x00C0,
	BLE_APPEARANCE_WATCH_SPORTS = 0x00C1,
	BLE_APPEARANCE_GENERIC_CLOCK = 0x0100,
	BLE_APPEARANCE_GENERIC_DISPLAY = 0x0140,
	BLE_APPEARANCE_GENERIC_REMOTE_CONTROL = 0x0180,
	BLE_APPEARANCE_GENERIC_EYE_GLASSES = 0x01C0,
	BLE_APPEARANCE_GENERIC_TAG = 0x0200,
	BLE_APPEARANCE_GENERIC_KEYRING = 0x0240,
	BLE_APPEARANCE_GENERIC_MEDIA_PLAYER = 0x0280,
	BLE_APPEARANCE_GENERIC_BARCODE_SCANNER = 0x02C0,
	BLE_APPEARANCE_GENERIC_THERMOMETER = 0x0300,
	BLE_APPEARANCE_THERMOMETER_EAR = 0x0301,
	BLE_APPEARANCE_GENERIC_HEART_RATE_SENSOR = 0x0340,
	BLE_APPEARANCE_HEART_RATE_BELT = 0x0341,
	BLE_APPEARANCE_GENERIC_BLOOD_PRESSURE = 0x0380,
	BLE_APPEARANCE_BLOOD_PRESSURE_ARM = 0x0381,
	BLE_APPEARANCE_BLOOD_PRESSURE_WRIST = 0x0382,
	BLE_APPEARANCE_GENERIC_HID = 0x03C0,
	BLE_APPEARANCE_HID_KEYBOARD = 0x03C1,
	BLE_APPEARANCE_HID_MOUSE = 0x03C2,
	BLE_APPEARANCE_HID_JOYSTICK = 0x03C3,
	BLE_APPEARANCE_HID_GAMEPAD = 0x03C4,
	BLE_APPEARANCE_HID_DIGITIZER_TABLET = 0x03C5,
	BLE_APPEARANCE_HID_CARD_READER = 0x03C6,
	BLE_APPEARANCE_HID_DIGITAL_PEN = 0x03C7,
	BLE_APPEARANCE_HID_BARCODE_SCANNER = 0x03C8,
	BLE_APPEARANCE_GENERIC_GLUCOSE_METER = 0x0400,
	BLE_APPEARANCE_GENERIC_RUNNING_WALKING_SENSOR = 0x0440,
	BLE_APPEARANCE_RUNNING_WALKING_IN_SHOE = 0x0441,
	BLE_APPEARANCE_RUNNING_WALKING_ON_SHOE = 0x0442,
	BLE_APPEARANCE_RUNNING_WALKING_ON_HIP = 0x0443,
	BLE_APPEARANCE_GENERIC_CYCLING = 0x0480,
	BLE_APPEARANCE_CYCLING_COMPUTER = 0x0481,
	BLE_APPEARANCE_CYCLING_SPEED_SENSOR = 0x0482,
	BLE_APPEARANCE_CYCLING_CADENCE_SENSOR = 0x0483,
	BLE_APPEARANCE_CYCLING_POWER_SENSOR = 0x0484,
	BLE_APPEARANCE_CYCLING_SPEED_CADENCE_SENSOR = 0x0485,
	BLE_APPEARANCE_GENERIC_CONTROL_DEVICE = 0x04C0,
	BLE_APPEARANCE_CONTROL_DEVICE_SWITCH = 0x04C1,
	BLE_APPEARANCE_CONTROL_DEVICE_MULTI_SWITCH = 0x04C2,
	BLE_APPEARANCE_CONTROL_DEVICE_BUTTON = 0x04C3,
	BLE_APPEARANCE_CONTROL_DEVICE_SLIDER = 0x04C4,
	BLE_APPEARANCE_CONTROL_DEVICE_ROTARY_DIAL = 0x04C5,
	BLE_APPEARANCE_CONTROL_DEVICE_TOUCH_PANEL = 0x04C6,
	BLE_APPEARANCE_GENERIC_NETWORK_DEVICE = 0x0500,
	BLE_APPEARANCE_NETWORK_DEVICE_ACCESS_POINT = 0x0501,
	BLE_APPEARANCE_GENERIC_SENSOR = 0x0540,
	BLE_APPEARANCE_SENSOR_MOTION = 0x0541,
	BLE_APPEARANCE_SENSOR_AIR_QUALITY = 0x0542,
	BLE_APPEARANCE_SENSOR_TEMPERATURE = 0x0543,
	BLE_APPEARANCE_SENSOR_HUMIDITY = 0x0544,
	BLE_APPEARANCE_GENERIC_AUDIO_DEVICE = 0x0580,
	BLE_APPEARANCE_AUDIO_DEVICE_HEADSET = 0x0581,
	BLE_APPEARANCE_AUDIO_DEVICE_HEADPHONES = 0x0582,
	BLE_APPEARANCE_AUDIO_DEVICE_SPEAKER = 0x0583,
	BLE_APPEARANCE_AUDIO_DEVICE_MICROPHONE = 0x0584,
	BLE_APPEARANCE_GENERIC_MEDICAL_DEVICE = 0x05C0,
	BLE_APPEARANCE_GENERIC_PULSE_OXIMETER = 0x0C00,
	BLE_APPEARANCE_PULSE_OXIMETER_FINGERTIP = 0x0C01,
	BLE_APPEARANCE_PULSE_OXIMETER_WRIST = 0x0C02,
	BLE_APPEARANCE_GENERIC_WEIGHT_SCALE = 0x0C40,
	BLE_APPEARANCE_GENERIC_PERSONAL_MOBILITY_DEVICE = 0x0C80,
	BLE_APPEARANCE_GENERIC_CONTINUOUS_GLUCOSE_MONITOR = 0x0CC0,
	BLE_APPEARANCE_GENERIC_INSULIN_PUMP = 0x0D00,
	BLE_APPEARANCE_GENERIC_MEDICATION_DELIVERY = 0x0D40,
	BLE_APPEARANCE_GENERIC_OUTDOOR_SPORTS_ACT = 0x1600,
	BLE_APPEARANCE_OUTDOOR_SPORTS_ACT_LOCATION_DISP = 0x1601,
	BLE_APPEARANCE_OUTDOOR_SPORTS_ACT_LOCATION_NAV = 0x1602,
	BLE_APPEARANCE_OUTDOOR_SPORTS_ACT_LOCATION_POD = 0x1603,
	BLE_APPEARANCE_OUTDOOR_SPORTS_ACT_LOCATION_NAV_POD = 0x1604
};

/*BLUETOOTH SIG SERVICES (16-BIT)*/
/* Core & Generic */
#define BLE_SVC_GENERIC_ACCESS { 0x00, 0x18 }
#define BLE_SVC_GENERIC_ATTRIBUTE { 0x01, 0x18 }
#define BLE_SVC_IMMEDIATE_ALERT { 0x02, 0x18 }
#define BLE_SVC_LINK_LOSS { 0x03, 0x18 }
#define BLE_SVC_TX_POWER { 0x04, 0x18 }
#define BLE_SVC_CURRENT_TIME { 0x05, 0x18 }
#define BLE_SVC_REFERENCE_TIME_UPDATE { 0x06, 0x18 }
#define BLE_SVC_NEXT_DST_CHANGE { 0x07, 0x18 }

/* Device Info & Power */
#define BLE_SVC_DEVICE_INFORMATION { 0x0A, 0x18 }
#define BLE_SVC_BATTERY_SERVICE { 0x0F, 0x18 }

/* Health, Fitness & Biometrics */
#define BLE_SVC_HEART_RATE { 0x0D, 0x18 }
#define BLE_SVC_HEALTH_THERMOMETER { 0x09, 0x18 }
#define BLE_SVC_BLOOD_PRESSURE { 0x10, 0x18 }
#define BLE_SVC_GLUCOSE { 0x08, 0x18 }
#define BLE_SVC_RUNNING_SPEED_AND_CADENCE { 0x14, 0x18 }
#define BLE_SVC_CYCLING_SPEED_AND_CADENCE { 0x16, 0x18 }
#define BLE_SVC_CYCLING_POWER { 0x18, 0x18 }
#define BLE_SVC_LOCATION_AND_NAVIGATION { 0x19, 0x18 }
#define BLE_SVC_PULSE_OXIMETER { 0x22, 0x18 }
#define BLE_SVC_WEIGHT_SCALE { 0x1D, 0x18 }
#define BLE_SVC_BODY_COMPOSITION { 0x1B, 0x18 }
#define BLE_SVC_USER_DATA { 0x1C, 0x18 }
#define BLE_SVC_CONTINUOUS_GLUCOSE_MONITORING { 0x1F, 0x18 }
#define BLE_SVC_INSULIN_DELIVERY { 0x3A, 0x18 }
#define BLE_SVC_PHYSICAL_ACTIVITY_MONITOR { 0x3E, 0x18 }

/* Environmental & Automation */
#define BLE_SVC_ENVIRONMENTAL_SENSING { 0x1A, 0x18 }
#define BLE_SVC_INDOOR_POSITIONING { 0x21, 0x18 }
#define BLE_SVC_AUTOMATION_IO { 0x15, 0x18 }

/* Human Interface & Media */
#define BLE_SVC_HUMAN_INTERFACE_DEVICE { 0x12, 0x18 }
#define BLE_SVC_SCAN_PARAMETERS { 0x13, 0x18 }
#define BLE_SVC_PHONE_ALERT_STATUS { 0x0E, 0x18 }
#define BLE_SVC_ALERT_NOTIFICATION { 0x11, 0x18 }
#define BLE_SVC_VOLUME_CONTROL { 0x44, 0x18 }
#define BLE_SVC_AUDIO_INPUT_CONTROL { 0x43, 0x18 }
#define BLE_SVC_MICROPHONE_CONTROL { 0x4D, 0x18 }

/*BLUETOOTH SIG CHARACTERISTICS (16-BIT)*/
/* Generic Access / Attribute (0x1800 / 0x1801) */
#define BLE_CHAR_DEVICE_NAME { 0x00, 0x2A }
#define BLE_CHAR_APPEARANCE { 0x01, 0x2A }
#define BLE_CHAR_PERIPHERAL_PRIVACY_FLAG { 0x02, 0x2A }
#define BLE_CHAR_RECONNECTION_ADDRESS { 0x03, 0x2A }
#define BLE_CHAR_PERIPHERAL_PREF_CONN_PARAMS { 0x04, 0x2A }
#define BLE_CHAR_SERVICE_CHANGED { 0x05, 0x2A }

/* Alert & Link Loss */
#define BLE_CHAR_ALERT_LEVEL { 0x06, 0x2A }
#define BLE_CHAR_TX_POWER_LEVEL { 0x07, 0x2A }

/* Time & Date */
#define BLE_CHAR_DATE_TIME { 0x08, 0x2A }
#define BLE_CHAR_DAY_OF_WEEK { 0x09, 0x2A }
#define BLE_CHAR_DAY_DATE_TIME { 0x0A, 0x2A }
#define BLE_CHAR_EXACT_TIME_256 { 0x0C, 0x2A }
#define BLE_CHAR_DST_OFFSET { 0x0D, 0x2A }
#define BLE_CHAR_TIME_ZONE { 0x0E, 0x2A }
#define BLE_CHAR_LOCAL_TIME_INFORMATION { 0x0F, 0x2A }
#define BLE_CHAR_TIME_WITH_DST { 0x11, 0x2A }
#define BLE_CHAR_TIME_ACCURACY { 0x12, 0x2A }
#define BLE_CHAR_TIME_SOURCE { 0x13, 0x2A }
#define BLE_CHAR_REFERENCE_TIME_INFO { 0x14, 0x2A }
#define BLE_CHAR_TIME_UPDATE_CONTROL_POINT { 0x16, 0x2A }
#define BLE_CHAR_TIME_UPDATE_STATE { 0x17, 0x2A }

/* Battery Service (0x180F) */
#define BLE_CHAR_BATTERY_LEVEL { 0x19, 0x2A }
#define BLE_CHAR_BATTERY_POWER_STATE { 0x1A, 0x2A }
#define BLE_CHAR_BATTERY_LEVEL_STATE { 0x1B, 0x2A }

/* Health & Medical Measurements */
#define BLE_CHAR_TEMPERATURE_MEASUREMENT { 0x1C, 0x2A }
#define BLE_CHAR_TEMPERATURE_TYPE { 0x1D, 0x2A }
#define BLE_CHAR_INTERMEDIATE_TEMPERATURE { 0x1E, 0x2A }
#define BLE_CHAR_HEART_RATE_MEASUREMENT { 0x37, 0x2A }
#define BLE_CHAR_BODY_SENSOR_LOCATION { 0x38, 0x2A }
#define BLE_CHAR_HEART_RATE_CONTROL_POINT { 0x39, 0x2A }
#define BLE_CHAR_BLOOD_PRESSURE_MEASUREMENT { 0x35, 0x2A }
#define BLE_CHAR_INTERMEDIATE_CUFF_PRESSURE { 0x36, 0x2A }
#define BLE_CHAR_BLOOD_PRESSURE_FEATURE { 0x49, 0x2A }
#define BLE_CHAR_GLUCOSE_MEASUREMENT { 0x18, 0x2A }
#define BLE_CHAR_GLUCOSE_MEASUREMENT_CONTEXT { 0x34, 0x2A }
#define BLE_CHAR_GLUCOSE_FEATURE { 0x51, 0x2A }

/* Device Information Service (0x180A) */
#define BLE_CHAR_SYSTEM_ID { 0x23, 0x2A }
#define BLE_CHAR_MODEL_NUMBER_STRING { 0x24, 0x2A }
#define BLE_CHAR_SERIAL_NUMBER_STRING { 0x25, 0x2A }
#define BLE_CHAR_FIRMWARE_REVISION_STRING { 0x26, 0x2A }
#define BLE_CHAR_HARDWARE_REVISION_STRING { 0x27, 0x2A }
#define BLE_CHAR_SOFTWARE_REVISION_STRING { 0x28, 0x2A }
#define BLE_CHAR_MANUFACTURER_NAME_STRING { 0x29, 0x2A }
#define BLE_CHAR_IEEE_11073_20601_REG_LIST { 0x2A, 0x2A }
#define BLE_CHAR_PNP_ID { 0x50, 0x2A }

/* Fitness & Motion (Steps, Distance, Cycling) */
#define BLE_CHAR_RSC_MEASUREMENT { 0x53, 0x2A }
#define BLE_CHAR_RSC_FEATURE { 0x54, 0x2A }
#define BLE_CHAR_SC_CONTROL_POINT { 0x55, 0x2A }
#define BLE_CHAR_CSC_MEASUREMENT { 0x5B, 0x2A }
#define BLE_CHAR_CSC_FEATURE { 0x5C, 0x2A }
#define BLE_CHAR_SENSOR_LOCATION { 0x5D, 0x2A }
#define BLE_CHAR_CYCLING_POWER_MEASUREMENT { 0x63, 0x2A }
#define BLE_CHAR_CYCLING_POWER_FEATURE { 0x65, 0x2A }
#define BLE_CHAR_CYCLING_POWER_CONTROL_POINT { 0x66, 0x2A }
#define BLE_CHAR_STEP_COUNTER_ACTIVITY_SUMMARY { 0xF0, 0x2A }

/* Environmental Sensing Service (0x181A) */
#define BLE_CHAR_TEMPERATURE { 0x6E, 0x2A }
#define BLE_CHAR_TEMPERATURE_CELSIUS { 0x1F, 0x2A }
#define BLE_CHAR_HUMIDITY { 0x6F, 0x2A }
#define BLE_CHAR_TRUE_WIND_SPEED { 0x70, 0x2A }
#define BLE_CHAR_TRUE_WIND_DIRECTION { 0x71, 0x2A }
#define BLE_CHAR_APPARENT_WIND_SPEED { 0x72, 0x2A }
#define BLE_CHAR_APPARENT_WIND_DIRECTION { 0x73, 0x2A }
#define BLE_CHAR_GUST_FACTOR { 0x74, 0x2A }
#define BLE_CHAR_POLLEN_CONCENTRATION { 0x75, 0x2A }
#define BLE_CHAR_UV_INDEX { 0x76, 0x2A }
#define BLE_CHAR_IRRADIANCE { 0x77, 0x2A }
#define BLE_CHAR_RAINFALL { 0x78, 0x2A }
#define BLE_CHAR_WIND_CHILL { 0x79, 0x2A }
#define BLE_CHAR_HEAT_INDEX { 0x7A, 0x2A }
#define BLE_CHAR_DEW_POINT { 0x7B, 0x2A }
#define BLE_CHAR_ELEVATION { 0x6C, 0x2A }
#define BLE_CHAR_PRESSURE { 0x6D, 0x2A }
#define BLE_CHAR_BAROMETRIC_PRESSURE_TREND { 0xA3, 0x2A }
#define BLE_CHAR_ILLUMINANCE { 0xFB, 0x2A }
#define BLE_CHAR_ILLUMINANCE16 { 0x1C, 0x2C }
#define BLE_CHAR_LUMINOUS_FLUX { 0xFC, 0x2A }

/* Pulse Oximeter (0x1822) */
#define BLE_CHAR_PLX_SPOT_CHECK_MEASUREMENT { 0x5E, 0x2A }
#define BLE_CHAR_PLX_CONTINUOUS_MEASUREMENT { 0x5F, 0x2A }
#define BLE_CHAR_PLX_FEATURES { 0x60, 0x2A }

/* User Data & Body Composition */
#define BLE_CHAR_BODY_COMPOSITION_FEATURE { 0x9B, 0x2A }
#define BLE_CHAR_BODY_COMPOSITION_MEASUREMENT { 0x9C, 0x2A }
#define BLE_CHAR_WEIGHT_MEASUREMENT { 0x9D, 0x2A }
#define BLE_CHAR_WEIGHT_SCALE_FEATURE { 0x9E, 0x2A }
#define BLE_CHAR_USER_CONTROL_POINT { 0x9F, 0x2A }
#define BLE_CHAR_AGE { 0x80, 0x2A }
#define BLE_CHAR_GENDER { 0x8C, 0x2A }
#define BLE_CHAR_FIRST_NAME { 0x8A, 0x2A }
#define BLE_CHAR_LAST_NAME { 0x90, 0x2A }
#define BLE_CHAR_HEIGHT { 0x8E, 0x2A }
#define BLE_CHAR_WEIGHT { 0x98, 0x2A }
#define BLE_CHAR_DATABASE_CHANGE_INCREMENT { 0x99, 0x2A }
#define BLE_CHAR_USER_INDEX { 0x9A, 0x2A }

/* Common Control & Record Points */
#define BLE_CHAR_RECORD_ACCESS_CONTROL_POINT { 0x52, 0x2A }

/* Human Interface Device (0x1812) */
#define BLE_CHAR_PROTOCOL_MODE { 0x4E, 0x2A }
#define BLE_CHAR_REPORT { 0x4D, 0x2A }
#define BLE_CHAR_REPORT_MAP { 0x4B, 0x2A }
#define BLE_CHAR_BOOT_KEYBOARD_INPUT_REPORT { 0x22, 0x2A }
#define BLE_CHAR_BOOT_KEYBOARD_OUTPUT_REPORT { 0x32, 0x2A }
#define BLE_CHAR_BOOT_MOUSE_INPUT_REPORT { 0x33, 0x2A }
#define BLE_CHAR_HID_INFORMATION { 0x4A, 0x2A }
#define BLE_CHAR_HID_CONTROL_POINT { 0x4C, 0x2A }

#endif /* BLE_SIG_UUIDS_H */
